### ISSUE TITLE
Publicising and blogging about re-design

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/asktheeu-theme#16]
Some ideas to communicate the re-design:

- Tweet when site goes live to say how great it looks, and that your site can look this good if you upgrade

**Blog posts:**

We could either:

- Do a blog post when it launches that covers: Why it's important to upgrade; look how good the site looks; your site can look this good if you upgrade. Perhaps @zarino and/or @wrightmartin could explain design decisions and talk more generally about design trends and how the way users interact with sites has changed? Could be a wider piece about good design perhaps? 

or 

- If site usage goes up after re-design, we could do a blog post a month or so after launch about the impact upgrading to new design has, as well as the above things. 

We'd need to check with AskTheEU if they were happy with blog post. 

What do we think? Any more ideas?

**Comment by garethrees** [comment]
- In mid-2015 we [redesigned WDTK](https://www.mysociety.org/2015/06/23/well-what-do-you-know-its-a-new-look-for-whatdotheyknow/), including a new homepage design
- Ported the updated look and feel to the base alavetelitheme in [Release 0.23](https://www.mysociety.org/2015/11/25/alaveteli-release-0-23/)
- Started from base alavetelitheme and ported their existing look and feel and customisations.

**Comment by MyfanwyNixon** [comment]
Those ideas look good to me, Gemma. 

Even if there's no tangible upturn on users, there are the intangibles, like the impression the site gives of being current and relevant.

Is there a mobile angle too? Does the site display better on mobile and how has that proportion of users changed over time?

**Comment by zarino** [comment]
Yes, the new layout is a total breath of fresh air on a small screen, compared to the old one which was really only built for desktop visitors.

I'll get some comments from a design angely together today and add them to this ticket.

**Comment by garethrees** [comment]
> Even if there's no tangible upturn on users, there are the intangibles, like the impression the site gives of being current and relevant.

Yeah, we decided in standup that we should talk about the redesign anyway, and hopefully do a more stats-y followup in 2-3 months

**Comment by zarino** [comment]
Design points:

* At least 50% of the traffic to most Alaveteli installs comes from mobile devices.
* Designing for mobile is partly about laying out the elements of the page in a sensible way for the smaller screen (which [the WDTK redesign](https://www.mysociety.org/2015/06/23/well-what-do-you-know-its-a-new-look-for-whatdotheyknow/), and later [Alaveteli release 0.23](https://www.mysociety.org/2015/11/25/alaveteli-release-0-23/) did)
* …But it's also about reducing the weight of the pages where possible. While the size of the files being sent to the user’s browser is important, it's actually often the *number* of files that can make a site feel slow, because each one incurs its own additional latency while it's being sent to your device.
* Alaveteli pages are already fairly lightweight, but where possible the redesign attempts to reduce the number of separate assets included for styling. The effect is that the new AskTheEU homepage requests roughly a third fewer files than the old one. File counts on other pages have been reduced too, so the site should feel snappier on poor connections and mobile devices.
* The new request pages are also more modern looking, with increased whitespace (eg: between the primary content on the page, like the email thread, and the secondary content like the sidebar) and improved contrast and type hierarchy, which should make them easier to quickly scan and find what you're looking for.
* Responsive design isn't just for mobiles either. The practices we use at mySociety also mean that users with visual impairments (or simply those who prefer bigger text on their web pages!) can zoom in using their browser’s zoom controls, and use the new site perfectly comfortably, with no degradation in experience. For example: zooming on the old design would eventually cause a horizontal scroll bar, which made reading lines of text very difficult. The new design fits to whatever window size and zoom level you have set.
* The base font size has also been increased from 12px to 16px, making text, especially on the Help and About pages, much easier to read. And links now have underlines, to better distinguish them for users with trouble seeing changes in colour.

**Comment by garethrees** [comment]
Should also talk about the fact that AskTheEU covers EU countries and could be an escalation point if your request doesn't get answered on your national Alaveteli install.

**Comment by luisaizuz** [comment]
Hello everyone! This is Luisa, from Access Info.
Here at the office we're all very excited with this re-launch!
Comms-wise, we were planning on focusing on social media as well as sending out a message to our main mailing list. Basically the we would:
- Announce the launch of new features and a new fancy look for AsktheEU.org;
- Make a special point about how awesome it is to be able to have a new mobile friendly version that allows you to ask the EU whatever you want, from wherever, whenever; 
- Make it short and to the point but in a lively and celebratory way; all while
- Addressing this message mainly to the site's (potential) users, encouraging them to see and test all the new features.
Also, if you publish a blog post we'll be happy to add a link to it for more info (maybe also more detail on the technical side of things).
Please let me know if this suits your plans. And, of course, we'll be happy to support (RT, etc) any other kind of comms you are planning on rolling out.

**Comment by MyfanwyNixon** [comment]
Hi Luisa *waves*

Yes, that all sounds great - keep us in the loop when your own stuff goes out, and equally we'll be happy to tweet/link etc.

**Comment by luisaizuz** [comment]
Perfect, Myf! Looks like Monday is the chosen day for the big launch, so we'll be in touch these next couple of days to let you know how we're getting on with our plans.
Please don't hesitate to do likewise!
Best from Madrid. :-)

**Comment by luisaizuz** [comment]
Hi all! :-)
We're all set for the launch tomorrow. We'll be tweeting both from Access Info's and AsktheEU's accounts, and a Facebook post will be published around 10.30 AM (post below). We'll also send that same message to our mailing lists.
Gemma sent us mySociety's blog post today, which is looking great! Whenever you have a link to the post, please past it on so we can add it to our comms.
The site, by the way, is looking fantastic. Great job, everyone!
Best from Madrid.

**
AsktheEU.org gets a new look! It’s smarter, faster, and mobile-friendly!

2016 is a big year for FOI, being the 250th anniversary of the world’s first Freedom of Information law, the Swedish law of 1766.

To celebrate the start of this special year, Access Info and mySociety are excited to be launching today the redesign of our EU request portal, www.asktheu.org.
But it’s not all about the looks! (Though it does look great, doesn’t it?)

AsktheEU.org is now quicker!
So you can search, ask and campaign at full speed.

AsktheEU.org is now responsive!
Because we know that half of you are likely to exercise your right to know from your mobile devices, we’ve made sure you can celebrate FOI’s 250th birthday the XXI Century way: requesting information via your smartphone. (But we cannot guarantee your answer from the European Commission will be as technologically advanced... Cc.: ‪#‎BerlaymontSnail‬)

Go ahead, take a tour! And don’t forget to ask the EU. :-)

www.asktheeu.org

You can also read more about the site's redesign and new features here: [Link to mySociety's post]

**

**Comment by Gemmamysoc** [comment]
Hey Luisa,

I'm just uploading the post blog now - will send you link in the next 
half an hour!

Cheers,
Gemma. :)

On 25/01/2016 18:38, luisaizuz wrote:
>
> Hi all! :-)
> We're all set for the launch tomorrow. We'll be tweeting both from 
> Access Info's and AsktheEU's accounts, and a Facebook post will be 
> published around 10.30 AM (post below). We'll also send that same 
> message to our mailing lists.
> Gemma sent us mySociety's blog post today, which is looking great! 
> Whenever you have a link to the post, please past it on so we can add 
> it to our comms.
> The site, by the way, is looking fantastic. Great job, everyone!
> Best from Madrid.
>
> **
> AsktheEU.org gets a new look! It’s smarter, faster, and mobile-friendly!
>
> 2016 is a big year for FOI, being the 250th anniversary of the world’s 
> first Freedom of Information law, the Swedish law of 1766.
>
> To celebrate the start of this special year, Access Info and mySociety 
> are excited to be launching today the redesign of our EU request 
> portal, www.asktheu.org <http://www.asktheu.org>.
> But it’s not all about the looks! (Though it does look great, doesn’t it?)
>
> AsktheEU.org is now quicker!
> So you can search, ask and campaign at full speed.
>
> AsktheEU.org is now responsive!
> Because we know that half of you are likely to exercise your right to 
> know from your mobile devices, we’ve made sure you can celebrate FOI’s 
> 250th birthday the XXI Century way: requesting information via your 
> smartphone. (But we cannot guarantee your answer from the European 
> Commission will be as technologically advanced... Cc.: 
> ‪#‎BerlaymontSnail‬)
>
> Go ahead, take a tour! And don’t forget to ask the EU. :-)
>
> www.asktheeu.org <http://www.asktheeu.org>
>
> You can also read more about the site's redesign and new features 
> here: [Link to mySociety's post]
>
> **
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mysociety/asktheeu-theme/issues/16#issuecomment-174614820>.
>

-- 
Gemma Humphrys
*Events Manager / Alaveteli Partnership Manager*
mySociety | mysociety.org <%E2%80%9Chttps://www.mysociety.org/%E2%80%9D>

**Comment by luisaizuz** [comment]
Great, thanks Gemma!

**Comment by Gemmamysoc** [comment]
Here it is: https://www.mysociety.org/2016/01/26/a-new-look-for-asktheeu-org/ Sorry for delay - was on a call :)

**Comment by luisaizuz** [comment]
Thank you Gemma! We've added it to our post. The news seem to be getting a pretty good response, so we'll keep on spreading the word throughout the week. :-)
